/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as AdminRouteImport } from './app/admin'
import { Route as IndexRouteImport } from './app/index'
import { Route as ApiSearchRouteImport } from './app/api/search'
import { Route as ApiAlbumsRouteImport } from './app/api/albums'
import { Route as AlbumIdRouteImport } from './app/album/$id'
import { Route as ApiItemsIdRouteImport } from './app/api/items/$id'
import { Route as ApiEventsReconcileRouteImport } from './app/api/events/reconcile'
import { Route as ApiAlbumIdRouteImport } from './app/api/album/$id'
import { Route as ApiAdminRefetchMusicbrainzRouteImport } from './app/api/admin/refetch-musicbrainz'
import { Route as ApiAdminImportHeatmapRouteImport } from './app/api/admin/import-heatmap'
import { Route as ApiAdminDeduplicateAlbumsRouteImport } from './app/api/admin/deduplicate-albums'
import { Route as ApiItemsIdRevealRouteImport } from './app/api/items/$id/reveal'
import { Route as ApiAlbumIdRevealRouteImport } from './app/api/album/$id/reveal'
import { Route as ApiAlbumIdRestoreRouteImport } from './app/api/album/$id/restore'
import { Route as ApiAlbumIdMusicbrainzRouteImport } from './app/api/album/$id/musicbrainz'
import { Route as ApiAlbumIdFolderRouteImport } from './app/api/album/$id/folder'
import { Route as ApiAlbumIdArtRouteImport } from './app/api/album/$id/art'
import { Route as ApiAlbumIdAlternativesRouteImport } from './app/api/album/$id/alternatives'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSearchRoute = ApiSearchRouteImport.update({
  id: '/api/search',
  path: '/api/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlbumsRoute = ApiAlbumsRouteImport.update({
  id: '/api/albums',
  path: '/api/albums',
  getParentRoute: () => rootRouteImport,
} as any)
const AlbumIdRoute = AlbumIdRouteImport.update({
  id: '/album/$id',
  path: '/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiItemsIdRoute = ApiItemsIdRouteImport.update({
  id: '/api/items/$id',
  path: '/api/items/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiEventsReconcileRoute = ApiEventsReconcileRouteImport.update({
  id: '/api/events/reconcile',
  path: '/api/events/reconcile',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAlbumIdRoute = ApiAlbumIdRouteImport.update({
  id: '/api/album/$id',
  path: '/api/album/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminRefetchMusicbrainzRoute =
  ApiAdminRefetchMusicbrainzRouteImport.update({
    id: '/api/admin/refetch-musicbrainz',
    path: '/api/admin/refetch-musicbrainz',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminImportHeatmapRoute = ApiAdminImportHeatmapRouteImport.update({
  id: '/api/admin/import-heatmap',
  path: '/api/admin/import-heatmap',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDeduplicateAlbumsRoute =
  ApiAdminDeduplicateAlbumsRouteImport.update({
    id: '/api/admin/deduplicate-albums',
    path: '/api/admin/deduplicate-albums',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiItemsIdRevealRoute = ApiItemsIdRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => ApiItemsIdRoute,
} as any)
const ApiAlbumIdRevealRoute = ApiAlbumIdRevealRouteImport.update({
  id: '/reveal',
  path: '/reveal',
  getParentRoute: () => ApiAlbumIdRoute,
} as any)
const ApiAlbumIdRestoreRoute = ApiAlbumIdRestoreRouteImport.update({
  id: '/restore',
  path: '/restore',
  getParentRoute: () => ApiAlbumIdRoute,
} as any)
const ApiAlbumIdMusicbrainzRoute = ApiAlbumIdMusicbrainzRouteImport.update({
  id: '/musicbrainz',
  path: '/musicbrainz',
  getParentRoute: () => ApiAlbumIdRoute,
} as any)
const ApiAlbumIdFolderRoute = ApiAlbumIdFolderRouteImport.update({
  id: '/folder',
  path: '/folder',
  getParentRoute: () => ApiAlbumIdRoute,
} as any)
const ApiAlbumIdArtRoute = ApiAlbumIdArtRouteImport.update({
  id: '/art',
  path: '/art',
  getParentRoute: () => ApiAlbumIdRoute,
} as any)
const ApiAlbumIdAlternativesRoute = ApiAlbumIdAlternativesRouteImport.update({
  id: '/alternatives',
  path: '/alternatives',
  getParentRoute: () => ApiAlbumIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/album/$id': typeof AlbumIdRoute
  '/api/albums': typeof ApiAlbumsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/admin/deduplicate-albums': typeof ApiAdminDeduplicateAlbumsRoute
  '/api/admin/import-heatmap': typeof ApiAdminImportHeatmapRoute
  '/api/admin/refetch-musicbrainz': typeof ApiAdminRefetchMusicbrainzRoute
  '/api/album/$id': typeof ApiAlbumIdRouteWithChildren
  '/api/events/reconcile': typeof ApiEventsReconcileRoute
  '/api/items/$id': typeof ApiItemsIdRouteWithChildren
  '/api/album/$id/alternatives': typeof ApiAlbumIdAlternativesRoute
  '/api/album/$id/art': typeof ApiAlbumIdArtRoute
  '/api/album/$id/folder': typeof ApiAlbumIdFolderRoute
  '/api/album/$id/musicbrainz': typeof ApiAlbumIdMusicbrainzRoute
  '/api/album/$id/restore': typeof ApiAlbumIdRestoreRoute
  '/api/album/$id/reveal': typeof ApiAlbumIdRevealRoute
  '/api/items/$id/reveal': typeof ApiItemsIdRevealRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/album/$id': typeof AlbumIdRoute
  '/api/albums': typeof ApiAlbumsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/admin/deduplicate-albums': typeof ApiAdminDeduplicateAlbumsRoute
  '/api/admin/import-heatmap': typeof ApiAdminImportHeatmapRoute
  '/api/admin/refetch-musicbrainz': typeof ApiAdminRefetchMusicbrainzRoute
  '/api/album/$id': typeof ApiAlbumIdRouteWithChildren
  '/api/events/reconcile': typeof ApiEventsReconcileRoute
  '/api/items/$id': typeof ApiItemsIdRouteWithChildren
  '/api/album/$id/alternatives': typeof ApiAlbumIdAlternativesRoute
  '/api/album/$id/art': typeof ApiAlbumIdArtRoute
  '/api/album/$id/folder': typeof ApiAlbumIdFolderRoute
  '/api/album/$id/musicbrainz': typeof ApiAlbumIdMusicbrainzRoute
  '/api/album/$id/restore': typeof ApiAlbumIdRestoreRoute
  '/api/album/$id/reveal': typeof ApiAlbumIdRevealRoute
  '/api/items/$id/reveal': typeof ApiItemsIdRevealRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/album/$id': typeof AlbumIdRoute
  '/api/albums': typeof ApiAlbumsRoute
  '/api/search': typeof ApiSearchRoute
  '/api/admin/deduplicate-albums': typeof ApiAdminDeduplicateAlbumsRoute
  '/api/admin/import-heatmap': typeof ApiAdminImportHeatmapRoute
  '/api/admin/refetch-musicbrainz': typeof ApiAdminRefetchMusicbrainzRoute
  '/api/album/$id': typeof ApiAlbumIdRouteWithChildren
  '/api/events/reconcile': typeof ApiEventsReconcileRoute
  '/api/items/$id': typeof ApiItemsIdRouteWithChildren
  '/api/album/$id/alternatives': typeof ApiAlbumIdAlternativesRoute
  '/api/album/$id/art': typeof ApiAlbumIdArtRoute
  '/api/album/$id/folder': typeof ApiAlbumIdFolderRoute
  '/api/album/$id/musicbrainz': typeof ApiAlbumIdMusicbrainzRoute
  '/api/album/$id/restore': typeof ApiAlbumIdRestoreRoute
  '/api/album/$id/reveal': typeof ApiAlbumIdRevealRoute
  '/api/items/$id/reveal': typeof ApiItemsIdRevealRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/album/$id'
    | '/api/albums'
    | '/api/search'
    | '/api/admin/deduplicate-albums'
    | '/api/admin/import-heatmap'
    | '/api/admin/refetch-musicbrainz'
    | '/api/album/$id'
    | '/api/events/reconcile'
    | '/api/items/$id'
    | '/api/album/$id/alternatives'
    | '/api/album/$id/art'
    | '/api/album/$id/folder'
    | '/api/album/$id/musicbrainz'
    | '/api/album/$id/restore'
    | '/api/album/$id/reveal'
    | '/api/items/$id/reveal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/album/$id'
    | '/api/albums'
    | '/api/search'
    | '/api/admin/deduplicate-albums'
    | '/api/admin/import-heatmap'
    | '/api/admin/refetch-musicbrainz'
    | '/api/album/$id'
    | '/api/events/reconcile'
    | '/api/items/$id'
    | '/api/album/$id/alternatives'
    | '/api/album/$id/art'
    | '/api/album/$id/folder'
    | '/api/album/$id/musicbrainz'
    | '/api/album/$id/restore'
    | '/api/album/$id/reveal'
    | '/api/items/$id/reveal'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/album/$id'
    | '/api/albums'
    | '/api/search'
    | '/api/admin/deduplicate-albums'
    | '/api/admin/import-heatmap'
    | '/api/admin/refetch-musicbrainz'
    | '/api/album/$id'
    | '/api/events/reconcile'
    | '/api/items/$id'
    | '/api/album/$id/alternatives'
    | '/api/album/$id/art'
    | '/api/album/$id/folder'
    | '/api/album/$id/musicbrainz'
    | '/api/album/$id/restore'
    | '/api/album/$id/reveal'
    | '/api/items/$id/reveal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AlbumIdRoute: typeof AlbumIdRoute
  ApiAlbumsRoute: typeof ApiAlbumsRoute
  ApiSearchRoute: typeof ApiSearchRoute
  ApiAdminDeduplicateAlbumsRoute: typeof ApiAdminDeduplicateAlbumsRoute
  ApiAdminImportHeatmapRoute: typeof ApiAdminImportHeatmapRoute
  ApiAdminRefetchMusicbrainzRoute: typeof ApiAdminRefetchMusicbrainzRoute
  ApiAlbumIdRoute: typeof ApiAlbumIdRouteWithChildren
  ApiEventsReconcileRoute: typeof ApiEventsReconcileRoute
  ApiItemsIdRoute: typeof ApiItemsIdRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/search': {
      id: '/api/search'
      path: '/api/search'
      fullPath: '/api/search'
      preLoaderRoute: typeof ApiSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/albums': {
      id: '/api/albums'
      path: '/api/albums'
      fullPath: '/api/albums'
      preLoaderRoute: typeof ApiAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/album/$id': {
      id: '/album/$id'
      path: '/album/$id'
      fullPath: '/album/$id'
      preLoaderRoute: typeof AlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$id': {
      id: '/api/items/$id'
      path: '/api/items/$id'
      fullPath: '/api/items/$id'
      preLoaderRoute: typeof ApiItemsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/events/reconcile': {
      id: '/api/events/reconcile'
      path: '/api/events/reconcile'
      fullPath: '/api/events/reconcile'
      preLoaderRoute: typeof ApiEventsReconcileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/album/$id': {
      id: '/api/album/$id'
      path: '/api/album/$id'
      fullPath: '/api/album/$id'
      preLoaderRoute: typeof ApiAlbumIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/refetch-musicbrainz': {
      id: '/api/admin/refetch-musicbrainz'
      path: '/api/admin/refetch-musicbrainz'
      fullPath: '/api/admin/refetch-musicbrainz'
      preLoaderRoute: typeof ApiAdminRefetchMusicbrainzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/import-heatmap': {
      id: '/api/admin/import-heatmap'
      path: '/api/admin/import-heatmap'
      fullPath: '/api/admin/import-heatmap'
      preLoaderRoute: typeof ApiAdminImportHeatmapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/deduplicate-albums': {
      id: '/api/admin/deduplicate-albums'
      path: '/api/admin/deduplicate-albums'
      fullPath: '/api/admin/deduplicate-albums'
      preLoaderRoute: typeof ApiAdminDeduplicateAlbumsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/items/$id/reveal': {
      id: '/api/items/$id/reveal'
      path: '/reveal'
      fullPath: '/api/items/$id/reveal'
      preLoaderRoute: typeof ApiItemsIdRevealRouteImport
      parentRoute: typeof ApiItemsIdRoute
    }
    '/api/album/$id/reveal': {
      id: '/api/album/$id/reveal'
      path: '/reveal'
      fullPath: '/api/album/$id/reveal'
      preLoaderRoute: typeof ApiAlbumIdRevealRouteImport
      parentRoute: typeof ApiAlbumIdRoute
    }
    '/api/album/$id/restore': {
      id: '/api/album/$id/restore'
      path: '/restore'
      fullPath: '/api/album/$id/restore'
      preLoaderRoute: typeof ApiAlbumIdRestoreRouteImport
      parentRoute: typeof ApiAlbumIdRoute
    }
    '/api/album/$id/musicbrainz': {
      id: '/api/album/$id/musicbrainz'
      path: '/musicbrainz'
      fullPath: '/api/album/$id/musicbrainz'
      preLoaderRoute: typeof ApiAlbumIdMusicbrainzRouteImport
      parentRoute: typeof ApiAlbumIdRoute
    }
    '/api/album/$id/folder': {
      id: '/api/album/$id/folder'
      path: '/folder'
      fullPath: '/api/album/$id/folder'
      preLoaderRoute: typeof ApiAlbumIdFolderRouteImport
      parentRoute: typeof ApiAlbumIdRoute
    }
    '/api/album/$id/art': {
      id: '/api/album/$id/art'
      path: '/art'
      fullPath: '/api/album/$id/art'
      preLoaderRoute: typeof ApiAlbumIdArtRouteImport
      parentRoute: typeof ApiAlbumIdRoute
    }
    '/api/album/$id/alternatives': {
      id: '/api/album/$id/alternatives'
      path: '/alternatives'
      fullPath: '/api/album/$id/alternatives'
      preLoaderRoute: typeof ApiAlbumIdAlternativesRouteImport
      parentRoute: typeof ApiAlbumIdRoute
    }
  }
}

interface ApiAlbumIdRouteChildren {
  ApiAlbumIdAlternativesRoute: typeof ApiAlbumIdAlternativesRoute
  ApiAlbumIdArtRoute: typeof ApiAlbumIdArtRoute
  ApiAlbumIdFolderRoute: typeof ApiAlbumIdFolderRoute
  ApiAlbumIdMusicbrainzRoute: typeof ApiAlbumIdMusicbrainzRoute
  ApiAlbumIdRestoreRoute: typeof ApiAlbumIdRestoreRoute
  ApiAlbumIdRevealRoute: typeof ApiAlbumIdRevealRoute
}

const ApiAlbumIdRouteChildren: ApiAlbumIdRouteChildren = {
  ApiAlbumIdAlternativesRoute: ApiAlbumIdAlternativesRoute,
  ApiAlbumIdArtRoute: ApiAlbumIdArtRoute,
  ApiAlbumIdFolderRoute: ApiAlbumIdFolderRoute,
  ApiAlbumIdMusicbrainzRoute: ApiAlbumIdMusicbrainzRoute,
  ApiAlbumIdRestoreRoute: ApiAlbumIdRestoreRoute,
  ApiAlbumIdRevealRoute: ApiAlbumIdRevealRoute,
}

const ApiAlbumIdRouteWithChildren = ApiAlbumIdRoute._addFileChildren(
  ApiAlbumIdRouteChildren,
)

interface ApiItemsIdRouteChildren {
  ApiItemsIdRevealRoute: typeof ApiItemsIdRevealRoute
}

const ApiItemsIdRouteChildren: ApiItemsIdRouteChildren = {
  ApiItemsIdRevealRoute: ApiItemsIdRevealRoute,
}

const ApiItemsIdRouteWithChildren = ApiItemsIdRoute._addFileChildren(
  ApiItemsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AlbumIdRoute: AlbumIdRoute,
  ApiAlbumsRoute: ApiAlbumsRoute,
  ApiSearchRoute: ApiSearchRoute,
  ApiAdminDeduplicateAlbumsRoute: ApiAdminDeduplicateAlbumsRoute,
  ApiAdminImportHeatmapRoute: ApiAdminImportHeatmapRoute,
  ApiAdminRefetchMusicbrainzRoute: ApiAdminRefetchMusicbrainzRoute,
  ApiAlbumIdRoute: ApiAlbumIdRouteWithChildren,
  ApiEventsReconcileRoute: ApiEventsReconcileRoute,
  ApiItemsIdRoute: ApiItemsIdRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
