import type { Metadata } from "next"
import {
    Geist,
    Geist_Mono,
    Inter,
    Space_Grotesk,
} from "next/font/google"

import "./globals.css"

import { cn } from "@/lib/ui/utils"
import { ThemeProvider } from "@/components/theme-provider"
import { Navbar } from "@/components/navbar"
import { CommandMenu } from "@/components/command-menu"

const spaceGroteskHeading = Space_Grotesk({
    subsets: ["latin"],
    variable: "--font-heading",
})

const inter = Inter({
    subsets: ["latin"],
    variable: "--font-sans",
})

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
})

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
})

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
}

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode
}>) {
    return (
        <html
            lang="en"
            suppressHydrationWarning
            className={cn(
                "h-full",
                "antialiased",
                geistSans.variable,
                geistMono.variable,
                "font-sans",
                inter.variable,
                spaceGroteskHeading.variable
            )}
        >
            <body className="min-h-full flex flex-col">
                <ThemeProvider
                    attribute="class"
                    defaultTheme="system"
                    enableSystem
                    disableTransitionOnChange
                >
                    <CommandMenu />
                    <header className="sticky top-0 z-50 backdrop-blur-md bg-black/60 border-b border-white/10">
                        <div className="container mx-auto px-4 py-3">
                            <Navbar />
                        </div>
                    </header>

                    <main className="flex-1">{children}</main>
                </ThemeProvider>
            </body>
        </html>
    )
}
